MorganHill <- read.csv("~/MorganHill.csv")
MountainView <- read.csv("~/MountainView.csv")
Milipitas <- read.csv("~/Milipitas.csv")
SantaClaraCountyCrimeData95.11 <- read.csv("C:/Users/Shruthi/Downloads/SantaClaraCountyCrimeData95-11.csv")
MMM<-rbind(MorganHill,MountainView[2:nrow(MountainView),],Milipitas[2:nrow(Milipitas),])
SantaClaraCounty<- SantaClaraCountyCrimeData95.11[1:187,1:12]
visualization01 <- gvisMotionChart(SantaClaraCounty,idvar="City", timevar="Year")
visualization02 <- gvisMotionChart(Milipitas,idvar="City", timevar="Year")
visualization03 <- gvisMotionChart(MorganHill,idvar="City", timevar="Year")
visualization04 <- gvisMotionChart(MMM,idvar="City", timevar="Year")
plot (visualization01)
plot (visualization02)
plot (visualization03)
plot (visualization04)